// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_onegate/test/api_endpoints/comprehensive_endpoint_test_suite.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:flutter/material.dart' as _i8;
import 'package:flutter_onegate/config/gate_config.dart' as _i3;
import 'package:flutter_onegate/data/datasources/gate_storage.dart' as _i2;
import 'package:flutter_onegate/data/datasources/remote_datasource.dart' as _i6;
import 'package:flutter_onegate/data/models/staff_model.dart' as _i13;
import 'package:flutter_onegate/domain/entities/visitor/purpose/purpose.dart'
    as _i10;
import 'package:flutter_onegate/domain/entities/visitor/visitor.dart' as _i9;
import 'package:flutter_onegate/domain/entities/visitor/visitorLog.dart'
    as _i11;
import 'package:flutter_onegate/presentation/features/visitor_checkin_flow/data/visitor_info.dart'
    as _i12;
import 'package:flutter_onegate/services/api_client/authenticated_api_client.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGateStorage_0 extends _i1.SmartFake implements _i2.GateStorage {
  _FakeGateStorage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGateConfig_1 extends _i1.SmartFake implements _i3.GateConfig {
  _FakeGateConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_2 extends _i1.SmartFake implements _i4.File {
  _FakeFile_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_3 extends _i1.SmartFake implements _i5.Dio {
  _FakeDio_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i5.Response<T1> {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_5 extends _i1.SmartFake implements _i5.BaseOptions {
  _FakeBaseOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_6 extends _i1.SmartFake
    implements _i5.HttpClientAdapter {
  _FakeHttpClientAdapter_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_7 extends _i1.SmartFake implements _i5.Transformer {
  _FakeTransformer_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_8 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRequestOptions_9 extends _i1.SmartFake
    implements _i5.RequestOptions {
  _FakeRequestOptions_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeaders_10 extends _i1.SmartFake implements _i5.Headers {
  _FakeHeaders_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_11 extends _i1.SmartFake implements Uri {
  _FakeUri_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i6.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GateStorage get gateStorage => (super.noSuchMethod(
        Invocation.getter(#gateStorage),
        returnValue: _FakeGateStorage_0(
          this,
          Invocation.getter(#gateStorage),
        ),
      ) as _i2.GateStorage);

  @override
  _i7.Future<Map<String, dynamic>> loginUser() => (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> callMember(
    String? mobile,
    _i8.BuildContext? context, {
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callMember,
          [
            mobile,
            context,
          ],
          {#name: name},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<dynamic>> getCallHistory(String? fromNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCallHistory,
          [fromNumber],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<dynamic>> fetchGates() => (super.noSuchMethod(
        Invocation.method(
          #fetchGates,
          [],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<dynamic>> fetchSocieties(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSocieties,
          [userId],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<void> sendFcmNotification(Map<String, dynamic>? requestData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFcmNotification,
          [requestData],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.GateConfig> fetchGateBaseDomain() => (super.noSuchMethod(
        Invocation.method(
          #fetchGateBaseDomain,
          [],
        ),
        returnValue: _i7.Future<_i3.GateConfig>.value(_FakeGateConfig_1(
          this,
          Invocation.method(
            #fetchGateBaseDomain,
            [],
          ),
        )),
      ) as _i7.Future<_i3.GateConfig>);

  @override
  _i7.Future<_i9.Visitor?> searchVisitor(String? mobileNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVisitor,
          [mobileNumber],
        ),
        returnValue: _i7.Future<_i9.Visitor?>.value(),
      ) as _i7.Future<_i9.Visitor?>);

  @override
  _i7.Future<List<_i10.PurposeCategory1>?> fetchPurpose() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPurpose,
          [],
        ),
        returnValue: _i7.Future<List<_i10.PurposeCategory1>?>.value(),
      ) as _i7.Future<List<_i10.PurposeCategory1>?>);

  @override
  _i7.Future<void> fetchAndStoreFaceRecConfig() => (super.noSuchMethod(
        Invocation.method(
          #fetchAndStoreFaceRecConfig,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i9.Visitor?> createVisitor(_i9.Visitor? visitor) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVisitor,
          [visitor],
        ),
        returnValue: _i7.Future<_i9.Visitor?>.value(),
      ) as _i7.Future<_i9.Visitor?>);

  @override
  _i7.Future<List<_i11.VisitorLog>?> fetchCardNumbers() => (super.noSuchMethod(
        Invocation.method(
          #fetchCardNumbers,
          [],
        ),
        returnValue: _i7.Future<List<_i11.VisitorLog>?>.value(),
      ) as _i7.Future<List<_i11.VisitorLog>?>);

  @override
  _i7.Future<_i11.VisitorLog?> checkIn(
    _i11.VisitorLog? visitorLog, [
    bool? statusallowed,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIn,
          [
            visitorLog,
            statusallowed,
          ],
        ),
        returnValue: _i7.Future<_i11.VisitorLog?>.value(),
      ) as _i7.Future<_i11.VisitorLog?>);

  @override
  _i7.Future<void> exportLogs(Map<String, dynamic>? visitorData) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportLogs,
          [visitorData],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.VisitorLog>> fetchCheckInLogs() => (super.noSuchMethod(
        Invocation.method(
          #fetchCheckInLogs,
          [],
        ),
        returnValue:
            _i7.Future<List<_i11.VisitorLog>>.value(<_i11.VisitorLog>[]),
      ) as _i7.Future<List<_i11.VisitorLog>>);

  @override
  _i7.Future<List<_i11.VisitorLog>> fetchAllLogs() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllLogs,
          [],
        ),
        returnValue:
            _i7.Future<List<_i11.VisitorLog>>.value(<_i11.VisitorLog>[]),
      ) as _i7.Future<List<_i11.VisitorLog>>);

  @override
  _i7.Future<List<_i11.VisitorLog>> fetchCheckOutLogs() => (super.noSuchMethod(
        Invocation.method(
          #fetchCheckOutLogs,
          [],
        ),
        returnValue:
            _i7.Future<List<_i11.VisitorLog>>.value(<_i11.VisitorLog>[]),
      ) as _i7.Future<List<_i11.VisitorLog>>);

  @override
  DateTime? tryParseDate(String? dateStr) =>
      (super.noSuchMethod(Invocation.method(
        #tryParseDate,
        [dateStr],
      )) as DateTime?);

  @override
  _i7.Future<Map<String, dynamic>> verifyPasscode({
    required String? companyId,
    String? passcode,
    int? id,
    String? mobile,
    bool? isStaff,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPasscode,
          [],
          {
            #companyId: companyId,
            #passcode: passcode,
            #id: id,
            #mobile: mobile,
            #isStaff: isStaff,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<dynamic>> getMember(int? companyId) => (super.noSuchMethod(
        Invocation.method(
          #getMember,
          [companyId],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<dynamic>> getSubCategoryId(int? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubCategoryId,
          [companyId],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<dynamic>> getMemberUnit(
    int? companyId,
    int? buildingId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemberUnit,
          [
            companyId,
            buildingId,
          ],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getBuilding(int? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBuilding,
          [companyId],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<dynamic>> getBuildingsList() => (super.noSuchMethod(
        Invocation.method(
          #getBuildingsList,
          [],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> sendOtpForSelfCheckIn(
          String? mobileNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtpForSelfCheckIn,
          [mobileNumber],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> verifySelfCheckin({
    required String? mobileNumber,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifySelfCheckin,
          [],
          {
            #mobileNumber: mobileNumber,
            #otp: otp,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<String?> sendOTP(String? mobileNumber) => (super.noSuchMethod(
        Invocation.method(
          #sendOTP,
          [mobileNumber],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> verifyOTP(
    String? mobileNumber,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [
            mobileNumber,
            otp,
          ],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> checkOut(_i11.VisitorLog? visitorLog) => (super.noSuchMethod(
        Invocation.method(
          #checkOut,
          [visitorLog],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> uploadParcelImage({
    required int? visitorLogId,
    required String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadParcelImage,
          [],
          {
            #visitorLogId: visitorLogId,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i12.VisitorInfo>> fetchApprovals({
    String? logID,
    bool? isSecondary,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchApprovals,
          [],
          {
            #logID: logID,
            #isSecondary: isSecondary,
          },
        ),
        returnValue:
            _i7.Future<List<_i12.VisitorInfo>>.value(<_i12.VisitorInfo>[]),
      ) as _i7.Future<List<_i12.VisitorInfo>>);

  @override
  int parseToInt(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #parseToInt,
          [value],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i7.Future<void> sendLogs(Map<String, dynamic>? visitorData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendLogs,
          [visitorData],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.Response<dynamic>?> readStatus(
    String? memberID,
    String? visitorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #readStatus,
          [
            memberID,
            visitorId,
          ],
        ),
        returnValue: _i7.Future<_i5.Response<dynamic>?>.value(),
      ) as _i7.Future<_i5.Response<dynamic>?>);

  @override
  _i7.Future<_i4.File> compressImage(_i4.File? file) => (super.noSuchMethod(
        Invocation.method(
          #compressImage,
          [file],
        ),
        returnValue: _i7.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #compressImage,
            [file],
          ),
        )),
      ) as _i7.Future<_i4.File>);

  @override
  _i7.Future<String?> uploadFile(
    _i4.File? thisfile,
    String? userMobile,
    int? companyId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            thisfile,
            userMobile,
            companyId,
          ],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<Map<String, dynamic>> getMembersList({String? buildingName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMembersList,
          [],
          {#buildingName: buildingName},
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<dynamic>?> getCachedData() => (super.noSuchMethod(
        Invocation.method(
          #getCachedData,
          [],
        ),
        returnValue: _i7.Future<List<dynamic>?>.value(),
      ) as _i7.Future<List<dynamic>?>);

  @override
  _i7.Future<void> cacheData(List<dynamic>? data) => (super.noSuchMethod(
        Invocation.method(
          #cacheData,
          [data],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cacheMeta(Map<String, dynamic>? meta) => (super.noSuchMethod(
        Invocation.method(
          #cacheMeta,
          [meta],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> getCachedMeta() => (super.noSuchMethod(
        Invocation.method(
          #getCachedMeta,
          [],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<dynamic>> getUnitsList(int? buildingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnitsList,
          [buildingId],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>?> fetchStaffById(int? staffId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchStaffById,
          [staffId],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<_i13.StaffModel>> fetchStaffList(String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchStaffList,
          [companyId],
        ),
        returnValue:
            _i7.Future<List<_i13.StaffModel>>.value(<_i13.StaffModel>[]),
      ) as _i7.Future<List<_i13.StaffModel>>);

  @override
  _i7.Future<void> makeExotelCall({
    required String? memberMobileNumber,
    required int? visitorId,
    required int? memberId,
    required int? visitorLogId,
    required String? purposeCategory,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeExotelCall,
          [],
          {
            #memberMobileNumber: memberMobileNumber,
            #visitorId: visitorId,
            #memberId: memberId,
            #visitorLogId: visitorLogId,
            #purposeCategory: purposeCategory,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<dynamic>> fetchParcels() => (super.noSuchMethod(
        Invocation.method(
          #fetchParcels,
          [],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> verifyParcelOtp(
    String? parcelId,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyParcelOtp,
          [
            parcelId,
            otp,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getParcelOtp(
    String? parcelId,
    String? mobileNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParcelOtp,
          [
            parcelId,
            mobileNumber,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<dynamic> fetchStaffCategory() => (super.noSuchMethod(
        Invocation.method(
          #fetchStaffCategory,
          [],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  _i7.Future<dynamic> addStaff(Map<String, dynamic>? staffData) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStaff,
          [staffData],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  _i7.Future<dynamic> editStaff(
    int? staffId,
    Map<String, dynamic>? staffData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editStaff,
          [
            staffId,
            staffData,
          ],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  _i7.Future<Map<String, dynamic>?> uploadStaffImages(
    _i4.File? file,
    int? companyId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadStaffImages,
          [
            file,
            companyId,
          ],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<bool> updateVisitor(_i9.Visitor? visitor) => (super.noSuchMethod(
        Invocation.method(
          #updateVisitor,
          [visitor],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [AuthenticatedApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticatedApiClient extends _i1.Mock
    implements _i14.AuthenticatedApiClient {
  MockAuthenticatedApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_3(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i5.Dio);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.Response<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i5.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_5(
          this,
          Invocation.getter(#options),
        ),
      ) as _i5.BaseOptions);

  @override
  set options(_i5.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_6(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i5.HttpClientAdapter);

  @override
  set httpClientAdapter(_i5.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_7(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i5.Transformer);

  @override
  set transformer(_i5.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_8(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i5.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i5.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i5.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i5.FileAccessMode? fileAccessMode = _i5.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);

  @override
  _i7.Future<_i5.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    _i5.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i5.FileAccessMode? fileAccessMode = _i5.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);

  @override
  _i7.Future<_i5.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i5.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> fetch<T>(_i5.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i7.Future<_i5.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i7.Future<_i5.Response<T>>);

  @override
  _i5.Dio clone({
    _i5.BaseOptions? options,
    _i5.Interceptors? interceptors,
    _i5.HttpClientAdapter? httpClientAdapter,
    _i5.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
          {
            #options: options,
            #interceptors: interceptors,
            #httpClientAdapter: httpClientAdapter,
            #transformer: transformer,
          },
        ),
        returnValue: _FakeDio_3(
          this,
          Invocation.method(
            #clone,
            [],
            {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            },
          ),
        ),
      ) as _i5.Dio);
}

/// A class which mocks [Response].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponse<T> extends _i1.Mock implements _i5.Response<T> {
  MockResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set data(T? _data) => super.noSuchMethod(
        Invocation.setter(
          #data,
          _data,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.RequestOptions get requestOptions => (super.noSuchMethod(
        Invocation.getter(#requestOptions),
        returnValue: _FakeRequestOptions_9(
          this,
          Invocation.getter(#requestOptions),
        ),
      ) as _i5.RequestOptions);

  @override
  set requestOptions(_i5.RequestOptions? _requestOptions) => super.noSuchMethod(
        Invocation.setter(
          #requestOptions,
          _requestOptions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set statusCode(int? _statusCode) => super.noSuchMethod(
        Invocation.setter(
          #statusCode,
          _statusCode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set statusMessage(String? _statusMessage) => super.noSuchMethod(
        Invocation.setter(
          #statusMessage,
          _statusMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Headers get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: _FakeHeaders_10(
          this,
          Invocation.getter(#headers),
        ),
      ) as _i5.Headers);

  @override
  set headers(_i5.Headers? _headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          _headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isRedirect => (super.noSuchMethod(
        Invocation.getter(#isRedirect),
        returnValue: false,
      ) as bool);

  @override
  set isRedirect(bool? _isRedirect) => super.noSuchMethod(
        Invocation.setter(
          #isRedirect,
          _isRedirect,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i5.RedirectRecord> get redirects => (super.noSuchMethod(
        Invocation.getter(#redirects),
        returnValue: <_i5.RedirectRecord>[],
      ) as List<_i5.RedirectRecord>);

  @override
  set redirects(List<_i5.RedirectRecord>? _redirects) => super.noSuchMethod(
        Invocation.setter(
          #redirects,
          _redirects,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> get extra => (super.noSuchMethod(
        Invocation.getter(#extra),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  set extra(Map<String, dynamic>? _extra) => super.noSuchMethod(
        Invocation.setter(
          #extra,
          _extra,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Uri get realUri => (super.noSuchMethod(
        Invocation.getter(#realUri),
        returnValue: _FakeUri_11(
          this,
          Invocation.getter(#realUri),
        ),
      ) as Uri);
}
