// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_onegate/test/api_endpoints/visitor_list_ordering_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter_onegate/services/api_service/onegate_api_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OneGateApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOneGateApiService extends _i1.Mock implements _i3.OneGateApiService {
  MockOneGateApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> updateUserProfile(Map<String, dynamic>? profileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [profileData],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<dynamic>> fetchSocieties() => (super.noSuchMethod(
        Invocation.method(
          #fetchSocieties,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>?> getSocietyDetails(String? societyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSocietyDetails,
          [societyId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>?> createVisitorEntry(
          Map<String, dynamic>? visitorData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVisitorEntry,
          [visitorData],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<dynamic>> getVisitorLogs({
    int? page = 1,
    int? limit = 20,
    String? status,
    DateTime? fromDate,
    DateTime? toDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisitorLogs,
          [],
          {
            #page: page,
            #limit: limit,
            #status: status,
            #fromDate: fromDate,
            #toDate: toDate,
          },
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<bool> updateVisitorStatus(
    String? visitorLogId,
    String? status, {
    String? remarks,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVisitorStatus,
          [
            visitorLogId,
            status,
          ],
          {#remarks: remarks},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<dynamic>> getMemberList({
    String? buildingId,
    String? unitId,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemberList,
          [],
          {
            #buildingId: buildingId,
            #unitId: unitId,
            #searchQuery: searchQuery,
          },
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> getGates() => (super.noSuchMethod(
        Invocation.method(
          #getGates,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<_i2.Response<T>> makeApiCall<T>({
    required String? method,
    required String? path,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeApiCall,
          [],
          {
            #method: method,
            #path: path,
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i4.Future<_i2.Response<T>>.value(_FakeResponse_0<T>(
          this,
          Invocation.method(
            #makeApiCall,
            [],
            {
              #method: method,
              #path: path,
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<T>>);
}
