import 'package:flutter_onegate/domain/entities/visitor.dart';

class VisitorMapper {
  static Visitor fromJson(Map<String, dynamic> json) {
    return Visitor(
      visitorId: json['visitor_id'],
      userId: json['user_id'],
      companyId: json['company_id'],
      unitId: json['unit_id'],
      firstName: json['first_name'],
      lastName: json['last_name'],
      gender: json['gender'],
      dob: json['dob'],
      mobile: json['mobile'],
      email: json['email'],
      imagePath: json['image_path'],
      comingFrom: json['coming_from'],
      city: json['city'],
      state: json['state'],
      country: json['country'],
      visitorType: json['visitor_type'],
      idProof: json['id_proof'],
      idProofType: json['id_proof_type'],
      idProofImage: json['id_proof_image'],
      idProofImagePath: json['id_proof_img_path'],
      passSerialNo: json['pass_serial_no'],
      visitorCode: json['code'],
      passType: json['pass_type'],
      passStartDate: json['pass_start_date'],
      passEndDate: json['pass_end_date'],
      passValidity: json['pass_validity'],
      cardNo: json['card_no'],
      status: json['status'],
      category: json['category'],
      isLogVisible: json['is_log_visible'],
      createdBy: json['created_by'],
      createdAt: json['created_at'],
      updatedBy: json['updated_by'],
      updatedAt: json['updated_at'],
      purpose: json['purpose'],
      buildingUnitId: json['building_unit_id'],
      imageLarge: json['image_large'],
      imageMedium: json['image_medium'],
      imageSmall: json['image_small'],
      isoCode: json['iso_code'],
      dialCode: json['dial_code'],
      staffType: json['staff_type'],
    );
  }

  static Map<String, dynamic> toJson(Visitor entity) {
    final Map<String, dynamic> data = {
      'visitor_id': entity.visitorId,
      'user_id': entity.userId,
      'company_id': entity.companyId,
      'unit_id': entity.unitId,
      'first_name': entity.firstName,
      'last_name': entity.lastName,
      'gender': entity.gender,
      'dob': entity.dob,
      'mobile': entity.mobile,
      'email': entity.email,
      'image_path': entity.imagePath,
      'coming_from': entity.comingFrom,
      'city': entity.city,
      'state': entity.state,
      'country': entity.country,
      'visitor_type': entity.visitorType,
      'id_proof': entity.idProof,
      'id_proof_type': entity.idProofType,
      'id_proof_image': entity.idProofImage,
      'id_proof_img_path': entity.idProofImagePath,
      'pass_serial_no': entity.passSerialNo,
      'code': entity.visitorCode,
      'pass_type': entity.passType,
      'pass_start_date': entity.passStartDate,
      'pass_end_date': entity.passEndDate,
      'pass_validity': entity.passValidity,
      'card_no': entity.cardNo,
      'status': entity.status,
      'category': entity.category,
      'is_log_visible': entity.isLogVisible,
      'created_by': entity.createdBy,
      'created_at': entity.createdAt,
      'updated_by': entity.updatedBy,
      'updated_at': entity.updatedAt,
      'purpose': entity.purpose,
      'building_unit_id': entity.buildingUnitId,
      'image_large': entity.imageLarge,
      'image_medium': entity.imageMedium,
      'image_small': entity.imageSmall,
      'iso_code': entity.isoCode,
      'dial_code': entity.dialCode,
      'staff_type': entity.staffType,
    };
    return data;
  }
}
