// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_onegate/test/services/background/data_observability_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_onegate/domain/entities/society/member.dart' as _i4;
import 'package:flutter_onegate/domain/entities/visitor/visitor.dart' as _i5;
import 'package:flutter_onegate/services/search/meilisearch_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MeilisearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeilisearchService extends _i1.Mock
    implements _i2.MeilisearchService {
  MockMeilisearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> initialize({
    String? host,
    String? apiKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #host: host,
            #apiKey: apiKey,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> indexResidents(List<_i4.Member>? residents) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexResidents,
          [residents],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> indexVisitors(List<_i5.Visitor>? visitors) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexVisitors,
          [visitors],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<Map<String, dynamic>>> searchResidents({
    required String? query,
    String? building,
    String? memberStatus,
    bool? approved,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchResidents,
          [],
          {
            #query: query,
            #building: building,
            #memberStatus: memberStatus,
            #approved: approved,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> searchVisitors({
    required String? query,
    bool? isStaff,
    DateTime? fromDate,
    DateTime? toDate,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVisitors,
          [],
          {
            #query: query,
            #isStaff: isStaff,
            #fromDate: fromDate,
            #toDate: toDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<String>> getSearchSuggestions(
    String? query, {
    String? index = r'residents',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchSuggestions,
          [query],
          {#index: index},
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> clearAllIndexes() => (super.noSuchMethod(
        Invocation.method(
          #clearAllIndexes,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isHealthy() => (super.noSuchMethod(
        Invocation.method(
          #isHealthy,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> getConnectionStatus() => (super.noSuchMethod(
        Invocation.method(
          #getConnectionStatus,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
