// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_onegate/test/services/session_manager/five_minute_token_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:flutter_onegate/data/datasources/gate_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GateStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGateStorage extends _i1.Mock implements _i2.GateStorage {
  MockGateStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveFaceRecConfig(Map<String, dynamic>? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFaceRecConfig,
          [config],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getFaceRecConfig() => (super.noSuchMethod(
        Invocation.method(
          #getFaceRecConfig,
          [],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> saveAccessToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveAccessToken,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveRefreshToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveRefreshToken,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveTokenExpiry(DateTime? expiryTime) => (super.noSuchMethod(
        Invocation.method(
          #saveTokenExpiry,
          [expiryTime],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveVisitorImageBase64(_i4.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveVisitorImageBase64,
          [imageFile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeVisitorImage() => (super.noSuchMethod(
        Invocation.method(
          #removeVisitorImage,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.File?> getVisitorImageBase64() => (super.noSuchMethod(
        Invocation.method(
          #getVisitorImageBase64,
          [],
        ),
        returnValue: _i3.Future<_i4.File?>.value(),
      ) as _i3.Future<_i4.File?>);

  @override
  _i3.Future<void> saveSocietyDetails(
    String? societyId,
    String? societyName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSocietyDetails,
          [
            societyId,
            societyName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveSocietyId(String? societyId) => (super.noSuchMethod(
        Invocation.method(
          #saveSocietyId,
          [societyId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getSocietyId() => (super.noSuchMethod(
        Invocation.method(
          #getSocietyId,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<bool> isTokenExpired() => (super.noSuchMethod(
        Invocation.method(
          #isTokenExpired,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> saveUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> saveUsername(String? username) => (super.noSuchMethod(
        Invocation.method(
          #saveUsername,
          [username],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveImage(String? image) => (super.noSuchMethod(
        Invocation.method(
          #saveImage,
          [image],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setComingFrom(String? comingFrom) => (super.noSuchMethod(
        Invocation.method(
          #setComingFrom,
          [comingFrom],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getComingFrom() => (super.noSuchMethod(
        Invocation.method(
          #getComingFrom,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> removeComingFrom() => (super.noSuchMethod(
        Invocation.method(
          #removeComingFrom,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getImage() => (super.noSuchMethod(
        Invocation.method(
          #getImage,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> getUsername() => (super.noSuchMethod(
        Invocation.method(
          #getUsername,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> saveUserEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #saveUserEmail,
          [email],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserEmail() => (super.noSuchMethod(
        Invocation.method(
          #getUserEmail,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> saveUserFullName(String? fullName) => (super.noSuchMethod(
        Invocation.method(
          #saveUserFullName,
          [fullName],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserFullName() => (super.noSuchMethod(
        Invocation.method(
          #getUserFullName,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> saveUserRoles(List<String>? roles) => (super.noSuchMethod(
        Invocation.method(
          #saveUserRoles,
          [roles],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getUserRoles() => (super.noSuchMethod(
        Invocation.method(
          #getUserRoles,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> saveSessionTimestamp(DateTime? timestamp) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSessionTimestamp,
          [timestamp],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getSessionTimestamp() => (super.noSuchMethod(
        Invocation.method(
          #getSessionTimestamp,
          [],
        ),
        returnValue: _i3.Future<DateTime?>.value(),
      ) as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> saveRole(String? role) => (super.noSuchMethod(
        Invocation.method(
          #saveRole,
          [role],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<dynamic, dynamic>> getSocietyDetails() => (super.noSuchMethod(
        Invocation.method(
          #getSocietyDetails,
          [],
        ),
        returnValue:
            _i3.Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}),
      ) as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<String?> getRole() => (super.noSuchMethod(
        Invocation.method(
          #getRole,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> saveMemberDetails(Map<String, dynamic>? memberDetails) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMemberDetails,
          [memberDetails],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getMemberDetails() => (super.noSuchMethod(
        Invocation.method(
          #getMemberDetails,
          [],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> clearStorage(String? key) => (super.noSuchMethod(
        Invocation.method(
          #clearStorage,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveVisitorLogId(String? visitorLogId) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveVisitorLogId,
          [visitorLogId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getVisitorLogId() => (super.noSuchMethod(
        Invocation.method(
          #getVisitorLogId,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> clearVisitorLogId() => (super.noSuchMethod(
        Invocation.method(
          #clearVisitorLogId,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearVisitorImage() => (super.noSuchMethod(
        Invocation.method(
          #clearVisitorImage,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool? getTooglevalue(String? key) => (super.noSuchMethod(Invocation.method(
        #getTooglevalue,
        [key],
      )) as bool?);

  @override
  _i3.Future<void> setToogleValue(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setToogleValue,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveMemberList(List<dynamic>? memberList) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMemberList,
          [memberList],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<dynamic>?> getMemberList() => (super.noSuchMethod(
        Invocation.method(
          #getMemberList,
          [],
        ),
        returnValue: _i3.Future<List<dynamic>?>.value(),
      ) as _i3.Future<List<dynamic>?>);

  @override
  _i3.Future<void> saveMemberApproval(bool? approval) => (super.noSuchMethod(
        Invocation.method(
          #saveMemberApproval,
          [approval],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool?> getMemberApproval() => (super.noSuchMethod(
        Invocation.method(
          #getMemberApproval,
          [],
        ),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<void> saveSelectedGate(
    String? gateName,
    String? gateId,
    String? gateType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedGate,
          [
            gateName,
            gateId,
            gateType,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String?>> getSelectedGate() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedGate,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, String?>>.value(<String, String?>{}),
      ) as _i3.Future<Map<String, String?>>);

  @override
  _i3.Future<String?> getGateType() => (super.noSuchMethod(
        Invocation.method(
          #getGateType,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setMeilisearchHost(String? host) => (super.noSuchMethod(
        Invocation.method(
          #setMeilisearchHost,
          [host],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getMeilisearchHost() => (super.noSuchMethod(
        Invocation.method(
          #getMeilisearchHost,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setMeilisearchApiKey(String? apiKey) => (super.noSuchMethod(
        Invocation.method(
          #setMeilisearchApiKey,
          [apiKey],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getMeilisearchApiKey() => (super.noSuchMethod(
        Invocation.method(
          #getMeilisearchApiKey,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setNotificationServiceEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationServiceEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> getNotificationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationServiceEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setNotificationWebhookUrl(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationWebhookUrl,
          [url],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getNotificationWebhookUrl() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationWebhookUrl,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setNotificationRetentionDays(int? days) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationRetentionDays,
          [days],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getNotificationRetentionDays() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationRetentionDays,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> setDataObservabilityEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDataObservabilityEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> getDataObservabilityEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getDataObservabilityEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setHealthCheckInterval(int? minutes) => (super.noSuchMethod(
        Invocation.method(
          #setHealthCheckInterval,
          [minutes],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getHealthCheckInterval() => (super.noSuchMethod(
        Invocation.method(
          #getHealthCheckInterval,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> setMeilisearchIndexSyncInterval(int? hours) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMeilisearchIndexSyncInterval,
          [hours],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getMeilisearchIndexSyncInterval() => (super.noSuchMethod(
        Invocation.method(
          #getMeilisearchIndexSyncInterval,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> clearVisitorSessionData() => (super.noSuchMethod(
        Invocation.method(
          #clearVisitorSessionData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
