// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_onegate/test/integration/comprehensive_integration_test_suite.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter/material.dart' as _i11;
import 'package:flutter_onegate/config/gate_config.dart' as _i4;
import 'package:flutter_onegate/data/datasources/gate_storage.dart' as _i3;
import 'package:flutter_onegate/data/datasources/remote_datasource.dart'
    as _i10;
import 'package:flutter_onegate/data/models/staff_model.dart' as _i16;
import 'package:flutter_onegate/domain/entities/visitor/purpose/purpose.dart'
    as _i13;
import 'package:flutter_onegate/domain/entities/visitor/visitor.dart' as _i12;
import 'package:flutter_onegate/domain/entities/visitor/visitorLog.dart'
    as _i14;
import 'package:flutter_onegate/presentation/features/visitor_checkin_flow/data/visitor_info.dart'
    as _i15;
import 'package:flutter_onegate/services/api_client/authenticated_api_client.dart'
    as _i9;
import 'package:flutter_onegate/services/auth_service/secure_token_manager.dart'
    as _i8;
import 'package:flutter_onegate/services/auth_service/unified_auth_service.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGateStorage_2 extends _i1.SmartFake implements _i3.GateStorage {
  _FakeGateStorage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGateConfig_3 extends _i1.SmartFake implements _i4.GateConfig {
  _FakeGateConfig_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_4 extends _i1.SmartFake implements _i5.File {
  _FakeFile_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UnifiedAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnifiedAuthService extends _i1.Mock
    implements _i6.UnifiedAuthService {
  MockUnifiedAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<bool> get authStateStream => (super.noSuchMethod(
        Invocation.getter(#authStateStream),
        returnValue: _i7.Stream<bool>.empty(),
      ) as _i7.Stream<bool>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> login() => (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<String?> getValidAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getValidAccessToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> refreshTokens() => (super.noSuchMethod(
        Invocation.method(
          #refreshTokens,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<String>> getUserRoles() => (super.noSuchMethod(
        Invocation.method(
          #getUserRoles,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<bool> hasRole(String? role) => (super.noSuchMethod(
        Invocation.method(
          #hasRole,
          [role],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SecureTokenManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureTokenManager extends _i1.Mock
    implements _i8.SecureTokenManager {
  MockSecureTokenManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> storeTokens({
    required String? accessToken,
    String? refreshToken,
    String? idToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeTokens,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #idToken: idToken,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getIdToken() => (super.noSuchMethod(
        Invocation.method(
          #getIdToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getValidAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getValidAccessToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> refreshTokens() => (super.noSuchMethod(
        Invocation.method(
          #refreshTokens,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>?> getUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthenticatedApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticatedApiClient extends _i1.Mock
    implements _i9.AuthenticatedApiClient {
  MockAuthenticatedApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.Response<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);

  @override
  _i7.Future<_i2.Response<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);

  @override
  _i7.Future<_i2.Response<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);

  @override
  _i7.Future<_i2.Response<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i2.Response<T>>);
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i10.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GateStorage get gateStorage => (super.noSuchMethod(
        Invocation.getter(#gateStorage),
        returnValue: _FakeGateStorage_2(
          this,
          Invocation.getter(#gateStorage),
        ),
      ) as _i3.GateStorage);

  @override
  _i7.Future<Map<String, dynamic>> loginUser() => (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> callMember(
    String? mobile,
    _i11.BuildContext? context, {
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callMember,
          [
            mobile,
            context,
          ],
          {#name: name},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<dynamic>> getCallHistory(String? fromNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCallHistory,
          [fromNumber],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<dynamic>> fetchGates() => (super.noSuchMethod(
        Invocation.method(
          #fetchGates,
          [],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<dynamic>> fetchSocieties(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSocieties,
          [userId],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<void> sendFcmNotification(Map<String, dynamic>? requestData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFcmNotification,
          [requestData],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i4.GateConfig> fetchGateBaseDomain() => (super.noSuchMethod(
        Invocation.method(
          #fetchGateBaseDomain,
          [],
        ),
        returnValue: _i7.Future<_i4.GateConfig>.value(_FakeGateConfig_3(
          this,
          Invocation.method(
            #fetchGateBaseDomain,
            [],
          ),
        )),
      ) as _i7.Future<_i4.GateConfig>);

  @override
  _i7.Future<_i12.Visitor?> searchVisitor(String? mobileNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVisitor,
          [mobileNumber],
        ),
        returnValue: _i7.Future<_i12.Visitor?>.value(),
      ) as _i7.Future<_i12.Visitor?>);

  @override
  _i7.Future<List<_i13.PurposeCategory1>?> fetchPurpose() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPurpose,
          [],
        ),
        returnValue: _i7.Future<List<_i13.PurposeCategory1>?>.value(),
      ) as _i7.Future<List<_i13.PurposeCategory1>?>);

  @override
  _i7.Future<void> fetchAndStoreFaceRecConfig() => (super.noSuchMethod(
        Invocation.method(
          #fetchAndStoreFaceRecConfig,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i12.Visitor?> createVisitor(_i12.Visitor? visitor) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVisitor,
          [visitor],
        ),
        returnValue: _i7.Future<_i12.Visitor?>.value(),
      ) as _i7.Future<_i12.Visitor?>);

  @override
  _i7.Future<List<_i14.VisitorLog>?> fetchCardNumbers() => (super.noSuchMethod(
        Invocation.method(
          #fetchCardNumbers,
          [],
        ),
        returnValue: _i7.Future<List<_i14.VisitorLog>?>.value(),
      ) as _i7.Future<List<_i14.VisitorLog>?>);

  @override
  _i7.Future<_i14.VisitorLog?> checkIn(
    _i14.VisitorLog? visitorLog, [
    bool? statusallowed,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIn,
          [
            visitorLog,
            statusallowed,
          ],
        ),
        returnValue: _i7.Future<_i14.VisitorLog?>.value(),
      ) as _i7.Future<_i14.VisitorLog?>);

  @override
  _i7.Future<void> exportLogs(Map<String, dynamic>? visitorData) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportLogs,
          [visitorData],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i14.VisitorLog>> fetchCheckInLogs() => (super.noSuchMethod(
        Invocation.method(
          #fetchCheckInLogs,
          [],
        ),
        returnValue:
            _i7.Future<List<_i14.VisitorLog>>.value(<_i14.VisitorLog>[]),
      ) as _i7.Future<List<_i14.VisitorLog>>);

  @override
  _i7.Future<List<_i14.VisitorLog>> fetchAllLogs() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllLogs,
          [],
        ),
        returnValue:
            _i7.Future<List<_i14.VisitorLog>>.value(<_i14.VisitorLog>[]),
      ) as _i7.Future<List<_i14.VisitorLog>>);

  @override
  _i7.Future<List<_i14.VisitorLog>> fetchCheckOutLogs() => (super.noSuchMethod(
        Invocation.method(
          #fetchCheckOutLogs,
          [],
        ),
        returnValue:
            _i7.Future<List<_i14.VisitorLog>>.value(<_i14.VisitorLog>[]),
      ) as _i7.Future<List<_i14.VisitorLog>>);

  @override
  DateTime? tryParseDate(String? dateStr) =>
      (super.noSuchMethod(Invocation.method(
        #tryParseDate,
        [dateStr],
      )) as DateTime?);

  @override
  _i7.Future<Map<String, dynamic>> verifyPasscode({
    required String? companyId,
    String? passcode,
    int? id,
    String? mobile,
    bool? isStaff,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPasscode,
          [],
          {
            #companyId: companyId,
            #passcode: passcode,
            #id: id,
            #mobile: mobile,
            #isStaff: isStaff,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<dynamic>> getMember(int? companyId) => (super.noSuchMethod(
        Invocation.method(
          #getMember,
          [companyId],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<dynamic>> getSubCategoryId(int? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubCategoryId,
          [companyId],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<dynamic>> getMemberUnit(
    int? companyId,
    int? buildingId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemberUnit,
          [
            companyId,
            buildingId,
          ],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getBuilding(int? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBuilding,
          [companyId],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<dynamic>> getBuildingsList() => (super.noSuchMethod(
        Invocation.method(
          #getBuildingsList,
          [],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> sendOtpForSelfCheckIn(
          String? mobileNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtpForSelfCheckIn,
          [mobileNumber],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> verifySelfCheckin({
    required String? mobileNumber,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifySelfCheckin,
          [],
          {
            #mobileNumber: mobileNumber,
            #otp: otp,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<String?> sendOTP(String? mobileNumber) => (super.noSuchMethod(
        Invocation.method(
          #sendOTP,
          [mobileNumber],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> verifyOTP(
    String? mobileNumber,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [
            mobileNumber,
            otp,
          ],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> checkOut(_i14.VisitorLog? visitorLog) => (super.noSuchMethod(
        Invocation.method(
          #checkOut,
          [visitorLog],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> uploadParcelImage({
    required int? visitorLogId,
    required String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadParcelImage,
          [],
          {
            #visitorLogId: visitorLogId,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i15.VisitorInfo>> fetchApprovals({
    String? logID,
    bool? isSecondary,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchApprovals,
          [],
          {
            #logID: logID,
            #isSecondary: isSecondary,
          },
        ),
        returnValue:
            _i7.Future<List<_i15.VisitorInfo>>.value(<_i15.VisitorInfo>[]),
      ) as _i7.Future<List<_i15.VisitorInfo>>);

  @override
  int parseToInt(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #parseToInt,
          [value],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i7.Future<void> sendLogs(Map<String, dynamic>? visitorData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendLogs,
          [visitorData],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.Response<dynamic>?> readStatus(
    String? memberID,
    String? visitorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #readStatus,
          [
            memberID,
            visitorId,
          ],
        ),
        returnValue: _i7.Future<_i2.Response<dynamic>?>.value(),
      ) as _i7.Future<_i2.Response<dynamic>?>);

  @override
  _i7.Future<_i5.File> compressImage(_i5.File? file) => (super.noSuchMethod(
        Invocation.method(
          #compressImage,
          [file],
        ),
        returnValue: _i7.Future<_i5.File>.value(_FakeFile_4(
          this,
          Invocation.method(
            #compressImage,
            [file],
          ),
        )),
      ) as _i7.Future<_i5.File>);

  @override
  _i7.Future<String?> uploadFile(
    _i5.File? thisfile,
    String? userMobile,
    int? companyId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            thisfile,
            userMobile,
            companyId,
          ],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<Map<String, dynamic>> getMembersList({String? buildingName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMembersList,
          [],
          {#buildingName: buildingName},
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<dynamic>?> getCachedData() => (super.noSuchMethod(
        Invocation.method(
          #getCachedData,
          [],
        ),
        returnValue: _i7.Future<List<dynamic>?>.value(),
      ) as _i7.Future<List<dynamic>?>);

  @override
  _i7.Future<void> cacheData(List<dynamic>? data) => (super.noSuchMethod(
        Invocation.method(
          #cacheData,
          [data],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cacheMeta(Map<String, dynamic>? meta) => (super.noSuchMethod(
        Invocation.method(
          #cacheMeta,
          [meta],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> getCachedMeta() => (super.noSuchMethod(
        Invocation.method(
          #getCachedMeta,
          [],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<dynamic>> getUnitsList(int? buildingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnitsList,
          [buildingId],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>?> fetchStaffById(int? staffId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchStaffById,
          [staffId],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<_i16.StaffModel>> fetchStaffList(String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchStaffList,
          [companyId],
        ),
        returnValue:
            _i7.Future<List<_i16.StaffModel>>.value(<_i16.StaffModel>[]),
      ) as _i7.Future<List<_i16.StaffModel>>);

  @override
  _i7.Future<void> makeExotelCall({
    required String? memberMobileNumber,
    required int? visitorId,
    required int? memberId,
    required int? visitorLogId,
    required String? purposeCategory,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeExotelCall,
          [],
          {
            #memberMobileNumber: memberMobileNumber,
            #visitorId: visitorId,
            #memberId: memberId,
            #visitorLogId: visitorLogId,
            #purposeCategory: purposeCategory,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<dynamic>> fetchParcels() => (super.noSuchMethod(
        Invocation.method(
          #fetchParcels,
          [],
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> verifyParcelOtp(
    String? parcelId,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyParcelOtp,
          [
            parcelId,
            otp,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getParcelOtp(
    String? parcelId,
    String? mobileNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParcelOtp,
          [
            parcelId,
            mobileNumber,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<dynamic> fetchStaffCategory() => (super.noSuchMethod(
        Invocation.method(
          #fetchStaffCategory,
          [],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  _i7.Future<dynamic> addStaff(Map<String, dynamic>? staffData) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStaff,
          [staffData],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  _i7.Future<dynamic> editStaff(
    int? staffId,
    Map<String, dynamic>? staffData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editStaff,
          [
            staffId,
            staffData,
          ],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  _i7.Future<Map<String, dynamic>?> uploadStaffImages(
    _i5.File? file,
    int? companyId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadStaffImages,
          [
            file,
            companyId,
          ],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<bool> updateVisitor(_i12.Visitor? visitor) => (super.noSuchMethod(
        Invocation.method(
          #updateVisitor,
          [visitor],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}
